### ISSUE TITLE
Use iTwinUI for status field and tool setting entry components

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#708]
**Is your feature request related to a problem? Please describe.**
Status fields and tool setting entries are not fully accessible or styled consistently.

**Describe the solution you'd like**
Replace the status field and tool setting entry components to use iTwinUI components. Specifically, make sure that the labels are accessible https://itwinui.bentley.com/docs/input#standalone

Tool-settings and status-bar are similar, make sure that code is reused (i.e. shared component or className), i.e.
```scss
.bar {
  background-color: var(--iui-color-background);
  height: var(--iui-component-height);
  border-color: var(--iui-color-border);
 
  &[data-placement="top"] {
    border-block-end: 1px solid;
  }

  &[data-placement="bottom"] {
    border-block-start: 1px solid;
  }
}
```

Additionally, [make sure that the size of the status-bar and tool-settings is consistent.](https://github.com/iTwin/appui/pull/758#issuecomment-1985857771)
