### ISSUE TITLE
Popouts: Sometimes stylesheets don't get copied over correctly to new window

### ISSUE THREAD

**Issue by Juliakas** [iTwin/appui#893]
### Describe the bug

Sometimes when styling components and combining shorthand properties with css variables and adding other related longhand properties to override something, document.stylesheet produces unexpected results that are then copied over to popout window and wrong styles are getting applied.

One example being:
```scss
.border-test {
  --border-color: red;
  border: 5px solid var(--border-color);
  border-bottom: 5px solid blue;
  height: 20px;
  width: 100px;
}
```
In main window it looks like so:
![image](https://github.com/iTwin/appui/assets/36437897/a6b008b9-bdb5-4338-a8b5-e7cb49baedbd)

And when popping out to new window, this gets produced upon inspecting: 
![image](https://github.com/iTwin/appui/assets/36437897/b3ddfaca-780f-4b47-b9e6-c6e402f35c10)
![image](https://github.com/iTwin/appui/assets/36437897/7642509b-3df5-4ff1-a18f-3054dfb57b21)

One interesting thing is that it works correctly when I use static value instead of variable or when I remove `border-bottom`.

This seems to be intended spec behavior that serializes `cssText` property like that. I found this chromium rejected issue:
https://issues.chromium.org/issues/40804066 and spec was linked to indicate intended behavior: https://drafts.csswg.org/css-variables/#pending-substitution-value

### To Reproduce

1. Add a simple div to a widget that can popout with a classname that defines the following styles:
    ```scss
    .border-test {
      --border-color: red;
      border: 5px solid var(--border-color);
      border-bottom: 5px solid blue;
      height: 20px;
      width: 100px;
    }
    ```
2. Open application, note applied borders for that div inside a widget, all 4 of them are applied with bottom one being different color.
3. Popout that widget.
4. Notice how only bottom border is applied.
5. Open devtools, inspect that div and note that stylesheets have deformed and lost information on remaining 3 borders.

### Expected Behavior

It is expected that when popping out widgets to a new window, all styles should be preserved as is and should not lose information. In this case it is expected that all borders retain same css properties as it had in main window.

### Desktop (please complete the applicable information)

**OS:** Windows 11
**Browser:** Microsoft Edge
**Browser version:** Version 126.0.2592.68 (Official build) (64-bit)
**Appui version:** 4.15.0 (reproduced on source)

### Additional context

I debugged source at `CopyStyles.ts` and noticed deformation was happening there. In my case I worked around this issue by being very verbose with longhand css properties and it seemed to work, but it can still cause issues as we just haven't discovered problems in other areas, maybe even in external code that we can't control.
